"use client";

import { useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import {
  DimensionEngine,
  type DimFormDef,
  type SectionSpec,
} from "../../[dimension]/DimensionClient";

// FOR KEEPER — the five sections on the Upload Hub, each an instance of the
// same dimension entry engine as the YOU dimensions (Figma frames
// 2337:6142 / 2337:7589 / 2337:8583 / 2337:9542 / 2337:10499).
// Only "Who they are" has a structured form (2337:6097).

// Who they are (form) — Figma 2337:6097. Same field component as History's
// form: 400px columns, 57px inputs, hints below; col3 fixed at 667px so the
// save button pins to the bottom. Banner facts line per 2337:6142:
// "Calls them: … · To you: … · Full name: … · Pronouns: … · Born: … ·
//  Birthplace: … · Lives: … · Speaks: … · Does: …".
const WHO_THEY_ARE_FORM: DimFormDef = {
  subtitle: "The things worth getting exactly right.",
  col3Height: 667,
  prose: [
    { key: "call_them",    label: "Calls them:" },
    { key: "to_you",       label: "To you:" },
    { key: "full_name",    label: "Full name:" },
    { key: "pronouns",     label: "Pronouns:" },
    { key: "birthday",     label: "Born:" },
    { key: "birthplace",   label: "Birthplace:" },
    { key: "lives_now",    label: "Lives:" },
    { key: "languages",    label: "Speaks:" },
    { key: "what_they_do", label: "Does:" },
  ],
  col1: [
    { key: "call_them",  label: "What you call them",   placeholder: "Your answer", hint: "e.g., their name, a nickname, what you actually call them", kind: "text",  multi: true },
    { key: "to_you",     label: "What they are to you", placeholder: "Your answer", hint: "e.g., son, daughter, friend, the person you raised",         kind: "text",  multi: true },
    { key: "birthday",   label: "Birthday",             placeholder: "Your answer", hint: "e.g., April 14, 1998",                                       kind: "text",  multi: false },
    { key: "birthplace", label: "Birthplace",           placeholder: "Your answer", hint: "e.g., the city and country they were born in",               kind: "place", multi: false },
    { key: "lives_now",  label: "Where they live now",  placeholder: "Your answer", hint: "e.g., the city and country, if you know it",                 kind: "place", multi: false },
  ],
  col2: [
    { key: "full_name",    label: "Full name",      placeholder: "Your answer", hint: "e.g., first and last",                                          kind: "text", multi: false },
    { key: "pronouns",     label: "Their pronouns", placeholder: "Your answer", hint: "e.g., he/him, she/her, they/them",                              kind: "text", multi: false },
    { key: "what_they_do", label: "What they do",   placeholder: "Your answer", hint: "e.g., teacher, still figuring it out, raising kids, studying", kind: "text", multi: true },
  ],
  col3: [
    { key: "languages", label: "Languages", placeholder: "Your answer", hint: "e.g., the ones they speak", kind: "language", multi: true },
  ],
};

// Full decks per the Notion doc "Ovyu Entry Inspiration Lines (Contract Specific)".
const KEEPER_PROMPTS: Record<string, string[]> = {
  "who-they-are": [
    "The day they came into your life, and how the room changed.",
    "What you first noticed about them, before you knew them at all.",
    "The moment they stopped being new to you and became yours.",
    "How the two of you found each other, in your own telling.",
    "The first time they made you laugh.",
    "The first real conversation you remember having with them.",
    "When you knew this one was going to matter.",
    "The version of them you met first, before life had worked on them.",
    "The quality in them you would name first to a stranger.",
    "What they are like when no one is watching.",
    "The thing they are better at than almost anyone you know.",
    "How they treat people who can do nothing for them.",
    "What they do when someone they love is hurting.",
    "The kind of courage they have, and where you have seen it.",
    "What makes them stubborn, and whether you love it or fight it.",
    "The way they walk into a room.",
    "How they handle being wrong.",
    "What they are like when they are truly happy.",
    "The gentleness in them that not everyone gets to see.",
    "The fire in them that surprises people.",
    "The trip, the year, or the season the two of you still talk about.",
    "A day with them you would live again exactly as it was.",
    "The hardest thing you went through together.",
    "An ordinary afternoon with them that somehow became a favorite.",
    "The tradition that belongs only to the two of you.",
    "The inside joke that still works after all these years.",
    "A time they showed up for you when it counted.",
    "A time you showed up for them, and what it meant.",
    "The argument between you that you are glad you had.",
    "The silence between you that says more than talking.",
    "The contradiction in them you find most endearing.",
    "The habit of theirs you tease them for and would miss terribly.",
    "The thing they always say.",
    "The way they laugh, described so it could be recognized.",
    "What they are ridiculous about.",
    "The small thing they do that is entirely, unmistakably them.",
    "The way they are in the morning.",
    "What they are like when they are tired, or hungry, or scared.",
    "What you know about where they come from that shaped who they are.",
    "The struggle in their life that made them who they are.",
    "The person in their life who shaped them most, in your eyes.",
    "What they have survived that they do not give themselves credit for.",
    "The chapter of their life you witnessed up close.",
    "What they were like at the age you knew them best.",
    "The dream they had early that you watched them chase.",
    "The version of them the world does not get to see.",
    "What they are to you, in words bigger than the label.",
    "The role they have played in your life that has no name.",
    "What your life would have been without them in it.",
    "The thing only they have ever understood about you.",
    "What they gave you that you never properly thanked them for.",
    "The way they changed you, quietly, over years.",
    "Who you are when you are with them.",
    "The part of yourself you only show them.",
    "The proudest you have ever been of them.",
    "A moment you watched them become who they were meant to be.",
    "The bravest thing you have seen them do.",
    "A time you watched them fall, and how they got up.",
    "The kindest thing you ever saw them do for someone else.",
    "The strongest you have ever seen them be.",
    "A moment their true character showed under pressure.",
    "The time they surprised even you.",
    "What their voice does to a room.",
    "The expression that crosses their face when they are truly moved.",
    "How they say your name.",
    "What their hands are like, and what they do with them.",
    "The way they take their coffee, their tea, their morning.",
    "What they always order, wear, carry, or reach for.",
    "The song, the smell, or the sight that is entirely them.",
    "The way they hug, or refuse to.",
    "The story about them you have told the most times.",
    "What people always say about them when they meet.",
    "The reputation they have, and whether it is fair.",
    "The nickname you have for them, and how it started.",
    "What they are like as a friend to others.",
    "What they are like when they love someone.",
    "The thing they believe about themselves that is wrong.",
    "The thing they believe about themselves that is exactly right.",
    "What scares them, that they would not admit.",
    "What they are proudest of in their own life.",
    "The way they have grown since you first knew them.",
    "The way they have stayed exactly the same.",
    "How they are with children, or animals, or strangers.",
    "The talent of theirs that goes unnoticed.",
    "The thing they make look easy that is not.",
    "The way they give a gift.",
    "The way they apologize, or struggle to.",
    "What they are like on their birthday.",
    "What they are like when the year has been hard.",
    "The compliment about them you have never said to their face.",
    "The photograph of them you carry in your mind.",
    "The day you understood them completely.",
    "What you hope they never lose about themselves.",
    "The thing about them that will outlast all of you.",
    "The way they make ordinary time feel like something.",
    "What it is like to be loved by them.",
    "What it is like to be known by them.",
    "The truest sentence you could write about who they are.",
    "The thing about them no one else has ever noticed.",
    "If someone had one minute to understand them, what you would tell them.",
  ],
  "who-theyre-becoming": [
    "The way they are different now than when you first knew them.",
    "The thing they are just starting to understand about themselves.",
    "What has softened in them lately.",
    "What has sharpened in them lately.",
    "The confidence you have watched arrive in them.",
    "The fear you have watched them start to shed.",
    "The new thing lighting them up right now.",
    "The way they carry themselves now that they did not before.",
    "The gift in them that has not fully arrived yet.",
    "What they are capable of that they have not touched.",
    "The door you can see them standing in front of.",
    "The strength in them still waking up.",
    "What they will be great at, once they let themselves.",
    "The talent they are still pretending is a hobby.",
    "The version of them that is three years away.",
    "What is coming for them that they cannot see yet.",
    "The thing they want right now more than they let on.",
    "The dream they have started saying out loud.",
    "What they are working toward, in their own words.",
    "The risk you can feel them getting ready to take.",
    "The life they are quietly building toward.",
    "What they are hungry for at this stage.",
    "The question they keep circling back to.",
    "What they are trying to become, whether or not they would say it.",
    "Who they are turning into, described to someone who has not seen them in years.",
    "The adult, the elder, the person they are growing into.",
    "The self they are shedding, and the one underneath.",
    "What is becoming truer about them every year.",
    "The person you always suspected was in there.",
    "Who they are when they stop performing.",
    "The values that are settling into place in them.",
    "The way their priorities are shifting.",
    "The habit you can see them outgrowing.",
    "The old story about themselves they are finally putting down.",
    "The relationship, place, or role they are ready to leave.",
    "What they used to need that they do not anymore.",
    "The version of themselves they are done being.",
    "The fear they are almost finished with.",
    "The decision you can feel them getting closer to.",
    "The tension in their life right now that will resolve into something.",
    "What they are figuring out about love right now.",
    "What they are figuring out about work right now.",
    "The thing they are unlearning.",
    "The belief of theirs that is being tested right now.",
    "Where you think they will be in ten years, and why.",
    "The kind of life you can already see taking shape for them.",
    "The person they will be when they finally believe in themselves.",
    "What they will look back on this year and understand.",
    "The chapter you can feel them about to begin.",
    "The direction they are pointed, even on the days they wander.",
    "The moment you are waiting to see them have.",
    "The thing you hope they discover about themselves soon.",
    "What you would give anything to watch them become.",
    "The turning point you can sense coming for them.",
    "What they are braver about now than they used to be.",
    "The way they are learning to ask for what they need.",
    "The thing they are finally letting themselves want.",
    "How they are learning to rest, or refusing to.",
    "The way they are becoming more themselves, not less.",
    "What is starting to matter to them that did not before.",
    "What is starting to matter less.",
    "The person they are becoming to the people who need them.",
    "The way they are stepping into responsibility.",
    "The way they are stepping into freedom.",
    "What they are building that they cannot yet see the shape of.",
    "The friendship, love, or work that is changing them right now.",
    "The loss that is quietly reshaping them.",
    "The wisdom arriving in them earlier than it should.",
    "The way they are becoming someone's safe place.",
    "What they are teaching themselves right now.",
    "The comfort zone they are about to leave.",
    "The identity they are trying on.",
    "What they will grow into that no one expects.",
    "The way struggle is changing them, for better or worse.",
    "What they are becoming that reminds you of someone.",
    "What they are becoming that is entirely their own.",
    "The version of them their younger self dreamed of.",
    "The way they are learning to forgive themselves.",
    "The thing they are getting brave enough to say.",
    "The person they are on the edge of trusting themselves to be.",
    "The next thing they will fall in love with.",
    "The way they are learning what they are worth.",
    "The person they will be when the current storm passes.",
    "The way they are learning to let people in.",
    "What you can see them making peace with.",
    "The strength they are building without noticing.",
    "The way they are becoming a beginning for someone else.",
    "The dream they are getting closer to admitting.",
    "The quiet transformation happening in them right now.",
    "What they are on the verge of that will change everything.",
    "The horizon they are walking toward.",
    "What they are becoming that the world is going to need.",
    "The becoming you most want to be around to witness.",
    "Who they will be at the age you are now.",
    "The way ambition is settling into them, or leaving them be.",
    "What they are learning to protect.",
    "The part of them the world is only beginning to see.",
    "The way they are becoming softer and harder at once.",
    "What they will thank this year for, later.",
    "If you could see the person they will finally become, what you believe you would find.",
  ],
  "what-you-want": [
    "The kind of life you hope they build.",
    "What you hope they measure their life by, in the end.",
    "The freedom you want for them.",
    "The kind of home you hope they make.",
    "What you hope they never settle for.",
    "The size of life you hope they let themselves want.",
    "What you hope they are brave enough to reach for.",
    "The mark you hope they leave, in their own way.",
    "The kind of love you hope finds them.",
    "What you hope they know about how they deserve to be treated.",
    "The kind of person you hope walks toward them.",
    "What you hope they never accept from anyone.",
    "The friendships you hope carry them.",
    "What you hope they learn to give in love.",
    "What you hope they let themselves receive.",
    "The family you hope they build or choose.",
    "The work you hope they find that does not feel like a cage.",
    "What you hope they do with their particular gift.",
    "The success you hope for them, defined your way.",
    "What you hope they are willing to fail at.",
    "The purpose you hope they stumble into.",
    "What you hope they build with their hands, their mind, or their heart.",
    "The ambition you hope they never apologize for.",
    "What you hope they walk away from, even if it looks like giving up.",
    "The small daily joys you hope fill their life.",
    "The kind of ordinary morning you hope they wake to.",
    "What you hope always makes them laugh.",
    "The rituals you hope they keep.",
    "The city, the house, or the corner of the world you hope holds them.",
    "What you hope they always make time for.",
    "The pleasures you hope they never feel guilty about.",
    "The peace you hope becomes ordinary for them.",
    "The relationship with themselves you hope they grow into.",
    "What you hope they finally believe about their own worth.",
    "The voice in their head you hope softens.",
    "What you hope they forgive themselves for.",
    "The confidence you hope settles into them for good.",
    "What you hope they stop being afraid of.",
    "The peace you hope they make with their own story.",
    "What you hope they always protect in themselves.",
    "The pain you would take from their future if you could.",
    "The mistake you hope they do not have to make to learn.",
    "What you hope they never have to prove.",
    "The loneliness you hope they are spared.",
    "What you hope never hardens in them.",
    "The kind of person you hope they learn to walk away from.",
    "What you hope they never lose in the trying.",
    "The bitterness you hope never finds them.",
    "The people you hope find them.",
    "The kind of belonging you hope they land in.",
    "What you hope they discover about the world.",
    "The wonder you hope stays with them for life.",
    "The place you hope feels like home to them.",
    "What you hope they learn about themselves that you already know.",
    "The joy you hope surprises them.",
    "The faith, in something, you hope holds them up.",
    "What you hope for them the day they fall in love.",
    "What you hope for them the day their heart breaks.",
    "What you hope for them the day they become a parent, if they choose to.",
    "What you hope for them on the day they doubt everything.",
    "What you hope for them the first time they truly succeed.",
    "What you hope for them the first time they truly fail.",
    "What you hope for them when they are old.",
    "What you hope for them on an ordinary Tuesday years from now.",
    "The kind of courage you hope they grow into.",
    "What you hope they teach their own children, if they have them.",
    "The dream of theirs you hope they do not talk themselves out of.",
    "What you hope they say yes to.",
    "What you hope they finally say no to.",
    "The kind of friend you hope they become.",
    "The kind of friend you hope they are lucky enough to have.",
    "What you hope they do with their anger.",
    "What you hope they do with their grief.",
    "The adventure you hope they take.",
    "The risk you hope they are glad they took.",
    "What you hope money never does to them.",
    "What you hope success never does to them.",
    "The health you hope holds for them.",
    "The kind of rest you hope they allow themselves.",
    "What you hope they spend their one life on.",
    "The version of happiness you hope they stop chasing and start living.",
    "What you hope they hold onto when everything shakes.",
    "The softness you hope the world does not take from them.",
    "What you hope they always come back to.",
    "The kind of aging you hope for them.",
    "What you hope they know when they look in the mirror at sixty.",
    "The people you hope surround them at the end of their life.",
    "The dream you hope they hand to someone else one day.",
    "What you hope they build that outlasts them.",
    "The kind of love you hope they are still capable of after being hurt.",
    "What you hope they never stop being curious about.",
    "The peace you hope they find with the people who hurt them.",
    "What you hope they carry forever, and what you hope they let go of.",
    "The kind of luck you hope follows them.",
    "The mentor, the teacher, or the guide you hope crosses their path.",
    "What you hope they are generous with.",
    "The door you hope opens that they never thought to knock on.",
    "What you hope they let themselves believe is possible.",
    "The life you can picture for them on your most hopeful day.",
    "If you could guarantee them one thing about their future, what it would be.",
  ],
  "what-you-want-known": [
    "The thing you most want them to know about how much you love them.",
    "When you started loving them, and whether they know.",
    "The way you love them that you never put into words.",
    "What loving them has been like.",
    "Why you chose them, if it was a choice, or how you would explain it if it was not.",
    "The love you feel for them that is bigger than you can carry.",
    "What you want them to know on the days they feel unloved.",
    "How much of your heart they hold.",
    "How proud you are of them, and exactly what for.",
    "The thing they did that you have never stopped being proud of.",
    "What you see in them that the world has not caught up to yet.",
    "The strength in them you want them to know you noticed.",
    "What you admire about them that you never said.",
    "The moment you were prouder of them than you ever let on.",
    "What they overcame that you want on the record.",
    "The person they became that you always knew they could.",
    "What you are thankful they gave you.",
    "The way they made your life better that you never named.",
    "What you owe them that you never repaid.",
    "The moment they saved you, whether they knew it or not.",
    "What you are grateful they forgave you for.",
    "The gift of their presence you took for granted.",
    "What they taught you without trying.",
    "The debt of love you want them to know you felt.",
    "The thing you always meant to tell them.",
    "The compliment you swallowed too many times.",
    "What you were too proud, or too scared, to say out loud.",
    "The secret about how you feel that you kept.",
    "What you wish you had said more often.",
    "The truth about them you never told them to their face.",
    "The thing you hope they always suspected, even unsaid.",
    "What you would say if you knew they were listening right now.",
    "The thing you are sorry for.",
    "The moment you failed them that still sits with you.",
    "What you would take back if you could.",
    "The apology you owe them.",
    "What you hope they forgive you for.",
    "The way you were hard on them that you regret.",
    "What you got wrong about them, and when you realized it.",
    "The hurt between you that you want them to know you carried too.",
    "The best thing they ever gave you, and it was not a thing.",
    "What your life looked like before them, and after.",
    "The way they changed you for the better.",
    "What they made possible for you.",
    "The version of yourself they brought out.",
    "The way they loved you when you were hard to love.",
    "What they believed about you that got you through.",
    "The safety they gave you that you did not know you needed.",
    "The beauty in them they cannot see.",
    "What they are wrong to be ashamed of.",
    "The talent they dismiss that is real.",
    "The good they have done that they have forgotten.",
    "What they should stop apologizing for.",
    "The thing they hate about themselves that you love most.",
    "How much they are loved, by more people than they know.",
    "The impact they had that they never saw.",
    "The hard thing you want them to hear, said with love.",
    "The truth about themselves you hope they finally accept.",
    "What you need them to know before it is too late to say it.",
    "The thing you want them to hold onto when they doubt themselves.",
    "What you want them to remember on their worst day.",
    "The reassurance you want to leave them with.",
    "What you want them to know they are allowed to do.",
    "The permission you want to give them.",
    "That it was never their fault, if that is the truth.",
    "That you noticed, all the times they thought no one did.",
    "What you want them to know about their worth, in plain words.",
    "The thing you hope they never doubt about your love.",
    "What you want them to know you understood, even when you seemed not to.",
    "The way they made you laugh that you want them to remember.",
    "What you want them to know you would do all over again.",
    "The moment with them you would relive, and why.",
    "That you were paying attention, always.",
    "What you want them to know about the day you met.",
    "The reason they matter, stated once, cleanly.",
    "What you hope they tell others about you and them.",
    "The thing about them you bragged about when they were not around.",
    "What you want them to know you saw them do right.",
    "That you are not disappointed, if they fear you are.",
    "What you forgive them for, freely, before they even ask.",
    "The way you want them to remember being loved by you.",
    "What you want them to know about the fights you had.",
    "The truth about how much they were wanted.",
    "What you want them to know you were proud to be to them.",
    "The thing you hope outlives you in them.",
    "That you would choose them again.",
    "The nickname, the joke, the small thing you want them to keep.",
    "What you want them to know you meant, even when your words came out wrong.",
    "That they were enough, exactly as they were.",
    "The thing you want them to stop carrying.",
    "That your love for them did not come with an end date.",
    "What you want them to know on the day they need it most.",
    "The way they made the hard years bearable.",
    "What you want them to know you saw in them from the very start.",
    "The pride you felt that you were too awkward to show.",
    "What you want them to know you carried for them, quietly.",
    "The way knowing them made you better.",
    "What you want them to know is theirs, and always was.",
    "The single sentence you would leave them with, if it were the only one.",
    "The thing you have never said to anyone, that you want them to know.",
  ],
  advice: [
    "What to do on the days getting out of bed is the whole job.",
    "What you want them to remember when they feel completely alone.",
    "Where to put the pain when there is nowhere to put it.",
    "What actually helps, from someone who has been through it.",
    "What to do when they cannot see a way forward.",
    "Who to call, and who not to, when it all falls apart.",
    "What to do with a night that will not end.",
    "How to survive the first year of a loss.",
    "What to remember on the day everything finally goes right.",
    "How to hold a good thing without waiting for it to break.",
    "What you want them to remember on their wedding day, if that day comes.",
    "What to remember the day they hold their own child, if they choose to.",
    "How to celebrate without rushing past it.",
    "What to do with a win that no one else understands the size of.",
    "How to mark the big days that arrive later on.",
    "What to say yes to when the chance comes.",
    "How to know when someone is worth keeping.",
    "What to do when love gets hard, before walking away.",
    "How to apologize so it actually lands.",
    "When to fight for a relationship, and when to let it go.",
    "What to look for in a person, past the obvious.",
    "How to love someone without losing yourself.",
    "What to do after hurting someone you love.",
    "How to keep a friendship alive across years and distance.",
    "How to make a decision when both roads look right.",
    "What money is for, and what it is not.",
    "When to take the risk, and when to keep the steady thing.",
    "How to know when it is time to leave.",
    "What to do with work that pays but empties you.",
    "How to spot the opportunity that only looks like a detour.",
    "What to negotiate for, and what to let go.",
    "How to fail at something without it becoming who you are.",
    "What to do the morning after failing badly.",
    "How to forgive yourself for the thing you cannot undo.",
    "What every mistake is actually trying to teach.",
    "When to try again, and when the lesson is to stop.",
    "How to say sorry and mean it, then move.",
    "What to do with regret so it does not calcify.",
    "How to tell a mistake from a disaster.",
    "The mistakes worth making on purpose.",
    "How to read a person before trusting them.",
    "When to give someone a second chance, and when not to.",
    "How to spot the people who are good for you.",
    "What to do about the people who drain you.",
    "How to keep your own counsel in a loud crowd.",
    "When to walk away from someone, even someone you love.",
    "How to tell a real friend from a fair-weather one.",
    "What to do when someone shows you who they are.",
    "What to do when the voice in their head turns cruel.",
    "How to be alone without being lonely.",
    "What to do with fear before it makes the decision for them.",
    "How to rest without earning it first.",
    "What to do when they do not recognize themselves.",
    "How to be kind to themselves on the hard days.",
    "What to do with anger so it does not run them.",
    "How to sit with a feeling instead of running from it.",
    "The one thing you have learned that you wish someone had told you.",
    "What actually matters, when the noise clears.",
    "What you spent too long worrying about that never came.",
    "The thing you chased that was not worth it.",
    "What you would do differently, offered as a gift not a warning.",
    "The advice you ignored that turned out to be right.",
    "What gets better with age that no one warns you about.",
    "What you know now that you would tell your younger self, passed to them instead.",
    "The thing to always keep in the house.",
    "How to make the meal that fixes a bad day.",
    "What to do when the car, the money, or the plan breaks down.",
    "The trick for getting through a task you dread.",
    "How to write the hard message, or the hard letter.",
    "What to do the night before something that scares them.",
    "How to walk into a room where they know no one.",
    "The small habit that changes everything, kept up over years.",
    "When to speak up, and when silence is the stronger move.",
    "How to hold a boundary without guilt.",
    "What to do when everyone wants a piece of them.",
    "How to say no and mean it.",
    "When to ask for help, and how.",
    "What to do when pride is getting in the way.",
    "How to disappoint someone and survive it.",
    "When to trust the gut over the spreadsheet.",
    "What to do with jealousy when it shows up.",
    "How to be happy for someone when it is hard.",
    "What to do when they have outgrown their own life.",
    "How to start over when starting over feels impossible.",
    "What to do when they are the one who was wrong.",
    "How to grieve, when the time comes, and let it take the time it takes.",
    "What to do with a friendship that has quietly died.",
    "How to know when good enough is actually enough.",
    "What to do when they are tempted to become someone they are not.",
    "How to keep hope without lying to themselves.",
    "What to do when they are given more than they think they can handle.",
    "How to accept help, praise, or love without deflecting it.",
    "What to do when the plan falls apart the day of.",
    "How to tell the difference between fear and wisdom.",
    "What to do when they want to give up on someone.",
    "How to spend a life so it feels like it was theirs.",
    "The advice you hope they never need but should have anyway.",
    "What to remember when they are about to make the choice you would warn against.",
    "The one piece of counsel you would want in their pocket for everything.",
    "What you would say if they called you, right now, needing an answer.",
  ],
};

// Titles per the Figma frame banners (2337:6154 / 7600 / 8594 / 9553 / 10510).
const KEEPER_SECTIONS: Record<string, { label: string; formDef?: DimFormDef }> = {
  "who-they-are":        { label: "Who they are", formDef: WHO_THEY_ARE_FORM },
  "who-theyre-becoming": { label: "Who they are becoming" },
  "what-you-want":       { label: "What you want for them" },
  "what-you-want-known": { label: "What you want them to know" },
  advice:                { label: "Advice" },
};

export function KeeperSectionClient() {
  const { contractId: rawId, section: rawSection } = useParams<{ contractId: string; section: string }>();
  // Next.js static export may resolve the params to the SSG placeholder "_".
  // Recover the real values from the actual URL path (/upload/{id}/keeper/{section}).
  const contractId = (() => {
    if (rawId !== "_") return rawId;
    if (typeof window === "undefined") return rawId;
    const seg = window.location.pathname.split("/").filter(Boolean)[1];
    if (seg && seg !== "_") return seg;
    return sessionStorage.getItem("ovyu_contract_id") ?? rawId;
  })();
  const section = rawSection === "_" && typeof window !== "undefined"
    ? (window.location.pathname.split("/").filter(Boolean)[3] ?? rawSection)
    : rawSection;
  const cfg = KEEPER_SECTIONS[section];
  const router = useRouter();

  useEffect(() => {
    if (!cfg) router.replace(`/upload/${contractId}`);
  }, [cfg, contractId, router]);

  if (!cfg) return null;

  const spec: SectionSpec = {
    slug: section,
    label: cfg.label,
    formDef: cfg.formDef,
    prompts: KEEPER_PROMPTS[section] ?? [],
    backHref: `/upload/${contractId}`,
    // backLabel omitted — the engine labels it "For {keeper_name}" from the hub.
    proseWidth: 1064,   // banner prose width per 2337:6155
    keeperBanner: true, // centered banner + 10px title→prose gap per 2337:6151
  };

  return <DimensionEngine contractId={contractId} spec={spec} />;
}
